version: '3'
services:
  postgres-testing:
    image: 'postgres'
  client:
    command: sh -c "CI=true npm test"
    ports:
      - "3000:3000"
    build:
      dockerfile: Dockerfile.dev
      context: ./client-react/
    volumes:
      - ./client-react:/app
      - /app/node_modules
  api:
    depends_on:
      - postgres-testing
    # TODO add migrations after 'done;' below:
    command: bash -c 'while !</dev/tcp/postgres-testing/5432; do sleep 1; done; python -m unittest discover tests'

    build:
      dockerfile: Dockerfile.dev
      context: ./server/
    volumes:
      - ./server:/app
    ports:
      - "5000:5000"
    tty: true
    stdin_open: true
    environment:
      - PORT=5000
      - FLASK_ENV=testing
      - DB_HOST=postgres-testing
      - DB_USER=postgres
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_PASSWORD=
      # NOTE do this
      - PYTHONPATH=/app
      - HTTP_HOST=http://localhost:5000
      - NOMICS_API_KEY=foo
