export enum Type {
    // auth types
    LOGIN,
    LOGIN_FAILED,
    LOGIN_SUCCEEDED,
    REGISTER,
    REGISTER_FAILED,
    REGISTER_SUCCEEDED,
    LOGOUT,

    // coin types
    SET_COINS,

    // game types
    CREATE_GAME,
    CREATE_GAME_FAILED,
    SET_GAME,
    SET_GAME_FAILED,

    SET_REGISTRATION_ERROR,
    SET_LOGIN_ERROR,
    
    // notification types
    GET_NOTIFICATIONS,
    GET_NOTIFICATIONS_SUCCEEDED,
    GET_NOTIFICATIONS_FAILED,
    GET_PRICE_ALERTS,
    GET_PRICE_ALERTS_SUCCEEDED,
    GET_PRICE_ALERTS_FAILED,
    CREATE_PRICE_ALERT,
    CREATE_PRICE_ALERT_SUCCEEDED,
    CREATE_PRICE_ALERT_FAILED,
}
